services:
  rtltcp:
    build:
      dockerfile: docker/rtltcp/Dockerfile
    volumes:
      - /dev/bus/usb:/dev/bus/usb:ro
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      FREQUENCY: 432800000
      GAIN: 0
      SAMPLERATE: 1600000
    restart: always

  openwebrx:
    image: slechev/openwebrxplus-softmbe:1.2.74
    volumes:
      - ./openwebrx/var:/var/lib/openwebrx
      - ./openwebrx/etc:/etc/openwebrx
      - type: tmpfs
        target: /tmp/openwebrx
        tmpfs:
          size: 1G
    ports:
      - 8073:8073
    environment:
      TZ: Etc/UTC
    restart: always
