networks:
  proxy:

volumes:
  caddy_config:
  caddy_data:

services:
  caddy:
    restart: always
    image: caddy:2.8-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_config:/config
      - caddy_data:/data
      - ./htdocs:/htdocs
    networks:
      - proxy
    ports:
      - '80:80'
      - '443:443'
      - '2019:2019'
