services:
  rtltcp:
    build:
      dockerfile: docker/rtltcp/Dockerfile
    volumes:
      - /dev/bus/usb:/dev/bus/usb:ro
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      FREQUENCY: 145000000
      GAIN: 0
      SAMPLERATE: 2400000
    restart: always

  openwebrx:
    image: slechev/openwebrxplus-softmbe:1.2.74
    volumes:
      - ./openwebrx/var:/var/lib/openwebrx
      - ./openwebrx/etc:/etc/openwebrx
    tmpfs:
      - /tmp
    ports:
      - 8073:8073
    environment:
      TZ: Etc/UTC
      OPENWEBRX_ADMIN_USER: admin
      OPENWEBRX_ADMIN_PASSWORD: password
    restart: always
